apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/kasunbg/bookings:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/kasunbg/bookings:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bookings
        chartPath: charts/bookings
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/kasunbg/bookings'
          image.tag: '{{.DIGEST_HEX}}'
